name: Main

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate a Team Token
        id: get-team-token
        uses: ./
        with:
          api-token: ${{secrets.ORG_OR_USER_API_KEY}}
          team-id: "team-NEgNT4rDDiBadPi9"

      - name: Confirm Result
        run: |
          echo "------ENV VAR------"
          echo "TF_API_TOKEN variable: ${{env.TF_API_TOKEN}}"

          echo "------OUTPUTS------"
          echo "team_token: ${{steps.get-team-token.outputs.team_token}}"
          echo "description: ${{steps.get-team-token.outputs.description}}"
          echo "createdat: ${{steps.get-team-token.outputs.createdat}}"
          echo "expiredat: ${{steps.get-team-token.outputs.expiredat}}"
